[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.21"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
message_gateway_v4 = "CbohhnRPNAC6d8jx8yqqwhaMp6poYXXhp6YofBgc3y4f"

[programs.devnet]
message_gateway_v4 = "CbohhnRPNAC6d8jx8yqqwhaMp6poYXXhp6YofBgc3y4f"

[programs.testnet]
message_gateway_v4 = "CbohhnRPNAC6d8jx8yqqwhaMp6poYXXhp6YofBgc3y4f"

[programs.mainnet]
message_gateway_v4 = "CbohhnRPNAC6d8jx8yqqwhaMp6poYXXhp6YofBgc3y4f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keypairs/authority.json"

[scripts]
test = "npm test"

[test]
startup_wait = 10000
upgradeable = true
